version: "3.9"  # optional since v1.27.0

services:
  docker-gorm:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: "postgres"   # use latest postgres base image
    env_file:
      - .env          # Get environment variables from .env file
      # Set your environment variables here directly
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD =postgres
#      - POSTGRES_DB =gorm
    volumes:
#      - seed.sql:/docker-entrypoint-initdb.d/seed.sql # when migrating to database
      - database-data:/var/lib/postgresql/data/   #persist data even if container shuts down

volumes:
  database-data: